spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datajpa?serverTimezone=Asia/Seoul
    username: root
    password: 9434340

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true


  data:
    web:
      pageable:
        default-page-size: 20 # 디폴트 값 변경가능(글로벌)

  org.hibernate.SQL: debug

